// Code generated by define_gene; DO NOT EDIT.
package larkworkplace

import (
	_ "embed"
	"github.com/ZenLiuCN/engine"

	_ "github.com/ZenLiuCN/engine/modules/golang/context"
	_ "github.com/ZenLiuCN/engineX/modules/github/com/larksuite/oapi-sdk-go/v3/core"
	"github.com/larksuite/oapi-sdk-go/v3/service/workplace/v1"
)

var (
	//go:embed github_com_larksuite_oapi-sdk-go_v3_service_workplace_v1.d.ts
	GithubComLarksuiteOapiSdkGo3ServiceWorkplace1Define   []byte
	GithubComLarksuiteOapiSdkGo3ServiceWorkplace1Declared = map[string]any{
		"newBlockAccessDataBuilder":                    larkworkplace.NewBlockAccessDataBuilder,
		"newCustomWorkplaceAccessDataBuilder":          larkworkplace.NewCustomWorkplaceAccessDataBuilder,
		"newI18nNameBuilder":                           larkworkplace.NewI18nNameBuilder,
		"newSearchWorkplaceAccessDataReqBuilder":       larkworkplace.NewSearchWorkplaceAccessDataReqBuilder,
		"newSearchWorkplaceBlockAccessDataReqBuilder":  larkworkplace.NewSearchWorkplaceBlockAccessDataReqBuilder,
		"newTemplateWorkplaceAccessDataBuilder":        larkworkplace.NewTemplateWorkplaceAccessDataBuilder,
		"newWorkplaceAccessDataBuilder":                larkworkplace.NewWorkplaceAccessDataBuilder,
		"New":                                          larkworkplace.New,
		"newDepartmentIdBuilder":                       larkworkplace.NewDepartmentIdBuilder,
		"newRuleBuilder":                               larkworkplace.NewRuleBuilder,
		"newSearchCustomWorkplaceAccessDataReqBuilder": larkworkplace.NewSearchCustomWorkplaceAccessDataReqBuilder,
		"newWorkplaceUserNotificationBuilder":          larkworkplace.NewWorkplaceUserNotificationBuilder,
		"newAccessDataBuilder":                         larkworkplace.NewAccessDataBuilder,
		"newWorkplaceTenantNotificationBuilder":        larkworkplace.NewWorkplaceTenantNotificationBuilder,

		"emptySearchWorkplaceBlockAccessDataResp":         engine.Empty[larkworkplace.SearchWorkplaceBlockAccessDataResp],
		"emptyRefSearchWorkplaceBlockAccessDataResp":      engine.EmptyRefer[larkworkplace.SearchWorkplaceBlockAccessDataResp],
		"refOfSearchWorkplaceBlockAccessDataResp":         engine.ReferOf[larkworkplace.SearchWorkplaceBlockAccessDataResp],
		"unRefSearchWorkplaceBlockAccessDataResp":         engine.UnRefer[larkworkplace.SearchWorkplaceBlockAccessDataResp],
		"emptyWorkplaceUserNotification":                  engine.Empty[larkworkplace.WorkplaceUserNotification],
		"emptyRefWorkplaceUserNotification":               engine.EmptyRefer[larkworkplace.WorkplaceUserNotification],
		"refOfWorkplaceUserNotification":                  engine.ReferOf[larkworkplace.WorkplaceUserNotification],
		"unRefWorkplaceUserNotification":                  engine.UnRefer[larkworkplace.WorkplaceUserNotification],
		"emptyAccessData":                                 engine.Empty[larkworkplace.AccessData],
		"emptyRefAccessData":                              engine.EmptyRefer[larkworkplace.AccessData],
		"refOfAccessData":                                 engine.ReferOf[larkworkplace.AccessData],
		"unRefAccessData":                                 engine.UnRefer[larkworkplace.AccessData],
		"emptyBlockAccessData":                            engine.Empty[larkworkplace.BlockAccessData],
		"emptyRefBlockAccessData":                         engine.EmptyRefer[larkworkplace.BlockAccessData],
		"refOfBlockAccessData":                            engine.ReferOf[larkworkplace.BlockAccessData],
		"unRefBlockAccessData":                            engine.UnRefer[larkworkplace.BlockAccessData],
		"emptySearchWorkplaceBlockAccessDataRespData":     engine.Empty[larkworkplace.SearchWorkplaceBlockAccessDataRespData],
		"emptyRefSearchWorkplaceBlockAccessDataRespData":  engine.EmptyRefer[larkworkplace.SearchWorkplaceBlockAccessDataRespData],
		"refOfSearchWorkplaceBlockAccessDataRespData":     engine.ReferOf[larkworkplace.SearchWorkplaceBlockAccessDataRespData],
		"unRefSearchWorkplaceBlockAccessDataRespData":     engine.UnRefer[larkworkplace.SearchWorkplaceBlockAccessDataRespData],
		"emptySearchCustomWorkplaceAccessDataReq":         engine.Empty[larkworkplace.SearchCustomWorkplaceAccessDataReq],
		"emptyRefSearchCustomWorkplaceAccessDataReq":      engine.EmptyRefer[larkworkplace.SearchCustomWorkplaceAccessDataReq],
		"refOfSearchCustomWorkplaceAccessDataReq":         engine.ReferOf[larkworkplace.SearchCustomWorkplaceAccessDataReq],
		"unRefSearchCustomWorkplaceAccessDataReq":         engine.UnRefer[larkworkplace.SearchCustomWorkplaceAccessDataReq],
		"emptySearchCustomWorkplaceAccessDataResp":        engine.Empty[larkworkplace.SearchCustomWorkplaceAccessDataResp],
		"emptyRefSearchCustomWorkplaceAccessDataResp":     engine.EmptyRefer[larkworkplace.SearchCustomWorkplaceAccessDataResp],
		"refOfSearchCustomWorkplaceAccessDataResp":        engine.ReferOf[larkworkplace.SearchCustomWorkplaceAccessDataResp],
		"unRefSearchCustomWorkplaceAccessDataResp":        engine.UnRefer[larkworkplace.SearchCustomWorkplaceAccessDataResp],
		"emptySearchWorkplaceAccessDataResp":              engine.Empty[larkworkplace.SearchWorkplaceAccessDataResp],
		"emptyRefSearchWorkplaceAccessDataResp":           engine.EmptyRefer[larkworkplace.SearchWorkplaceAccessDataResp],
		"refOfSearchWorkplaceAccessDataResp":              engine.ReferOf[larkworkplace.SearchWorkplaceAccessDataResp],
		"unRefSearchWorkplaceAccessDataResp":              engine.UnRefer[larkworkplace.SearchWorkplaceAccessDataResp],
		"emptyV1":                                         engine.Empty[larkworkplace.V1],
		"emptyRefV1":                                      engine.EmptyRefer[larkworkplace.V1],
		"refOfV1":                                         engine.ReferOf[larkworkplace.V1],
		"unRefV1":                                         engine.UnRefer[larkworkplace.V1],
		"emptyDepartmentId":                               engine.Empty[larkworkplace.DepartmentId],
		"emptyRefDepartmentId":                            engine.EmptyRefer[larkworkplace.DepartmentId],
		"refOfDepartmentId":                               engine.ReferOf[larkworkplace.DepartmentId],
		"unRefDepartmentId":                               engine.UnRefer[larkworkplace.DepartmentId],
		"emptyI18nName":                                   engine.Empty[larkworkplace.I18nName],
		"emptyRefI18nName":                                engine.EmptyRefer[larkworkplace.I18nName],
		"refOfI18nName":                                   engine.ReferOf[larkworkplace.I18nName],
		"unRefI18nName":                                   engine.UnRefer[larkworkplace.I18nName],
		"emptyRule":                                       engine.Empty[larkworkplace.Rule],
		"emptyRefRule":                                    engine.EmptyRefer[larkworkplace.Rule],
		"refOfRule":                                       engine.ReferOf[larkworkplace.Rule],
		"unRefRule":                                       engine.UnRefer[larkworkplace.Rule],
		"emptySearchCustomWorkplaceAccessDataRespData":    engine.Empty[larkworkplace.SearchCustomWorkplaceAccessDataRespData],
		"emptyRefSearchCustomWorkplaceAccessDataRespData": engine.EmptyRefer[larkworkplace.SearchCustomWorkplaceAccessDataRespData],
		"refOfSearchCustomWorkplaceAccessDataRespData":    engine.ReferOf[larkworkplace.SearchCustomWorkplaceAccessDataRespData],
		"unRefSearchCustomWorkplaceAccessDataRespData":    engine.UnRefer[larkworkplace.SearchCustomWorkplaceAccessDataRespData],
		"emptyTemplateWorkplaceAccessData":                engine.Empty[larkworkplace.TemplateWorkplaceAccessData],
		"emptyRefTemplateWorkplaceAccessData":             engine.EmptyRefer[larkworkplace.TemplateWorkplaceAccessData],
		"refOfTemplateWorkplaceAccessData":                engine.ReferOf[larkworkplace.TemplateWorkplaceAccessData],
		"unRefTemplateWorkplaceAccessData":                engine.UnRefer[larkworkplace.TemplateWorkplaceAccessData],
		"emptySearchWorkplaceBlockAccessDataReq":          engine.Empty[larkworkplace.SearchWorkplaceBlockAccessDataReq],
		"emptyRefSearchWorkplaceBlockAccessDataReq":       engine.EmptyRefer[larkworkplace.SearchWorkplaceBlockAccessDataReq],
		"refOfSearchWorkplaceBlockAccessDataReq":          engine.ReferOf[larkworkplace.SearchWorkplaceBlockAccessDataReq],
		"unRefSearchWorkplaceBlockAccessDataReq":          engine.UnRefer[larkworkplace.SearchWorkplaceBlockAccessDataReq],
		"emptyWorkplaceAccessData":                        engine.Empty[larkworkplace.WorkplaceAccessData],
		"emptyRefWorkplaceAccessData":                     engine.EmptyRefer[larkworkplace.WorkplaceAccessData],
		"refOfWorkplaceAccessData":                        engine.ReferOf[larkworkplace.WorkplaceAccessData],
		"unRefWorkplaceAccessData":                        engine.UnRefer[larkworkplace.WorkplaceAccessData],
		"emptySearchWorkplaceAccessDataReq":               engine.Empty[larkworkplace.SearchWorkplaceAccessDataReq],
		"emptyRefSearchWorkplaceAccessDataReq":            engine.EmptyRefer[larkworkplace.SearchWorkplaceAccessDataReq],
		"refOfSearchWorkplaceAccessDataReq":               engine.ReferOf[larkworkplace.SearchWorkplaceAccessDataReq],
		"unRefSearchWorkplaceAccessDataReq":               engine.UnRefer[larkworkplace.SearchWorkplaceAccessDataReq],
		"emptySearchWorkplaceAccessDataRespData":          engine.Empty[larkworkplace.SearchWorkplaceAccessDataRespData],
		"emptyRefSearchWorkplaceAccessDataRespData":       engine.EmptyRefer[larkworkplace.SearchWorkplaceAccessDataRespData],
		"refOfSearchWorkplaceAccessDataRespData":          engine.ReferOf[larkworkplace.SearchWorkplaceAccessDataRespData],
		"unRefSearchWorkplaceAccessDataRespData":          engine.UnRefer[larkworkplace.SearchWorkplaceAccessDataRespData],
		"emptyCustomWorkplaceAccessData":                  engine.Empty[larkworkplace.CustomWorkplaceAccessData],
		"emptyRefCustomWorkplaceAccessData":               engine.EmptyRefer[larkworkplace.CustomWorkplaceAccessData],
		"refOfCustomWorkplaceAccessData":                  engine.ReferOf[larkworkplace.CustomWorkplaceAccessData],
		"unRefCustomWorkplaceAccessData":                  engine.UnRefer[larkworkplace.CustomWorkplaceAccessData],
		"emptyWorkplaceTenantNotification":                engine.Empty[larkworkplace.WorkplaceTenantNotification],
		"emptyRefWorkplaceTenantNotification":             engine.EmptyRefer[larkworkplace.WorkplaceTenantNotification],
		"refOfWorkplaceTenantNotification":                engine.ReferOf[larkworkplace.WorkplaceTenantNotification],
		"unRefWorkplaceTenantNotification":                engine.UnRefer[larkworkplace.WorkplaceTenantNotification]}
)

func init() {
	engine.RegisterModule(GithubComLarksuiteOapiSdkGo3ServiceWorkplace1Module{})
}

type GithubComLarksuiteOapiSdkGo3ServiceWorkplace1Module struct{}

func (S GithubComLarksuiteOapiSdkGo3ServiceWorkplace1Module) Identity() string {
	return "github.com/larksuite/oapi-sdk-go/v3/service/workplace/v1"
}
func (S GithubComLarksuiteOapiSdkGo3ServiceWorkplace1Module) TypeDefine() []byte {
	return GithubComLarksuiteOapiSdkGo3ServiceWorkplace1Define
}
func (S GithubComLarksuiteOapiSdkGo3ServiceWorkplace1Module) Exports() map[string]any {
	return GithubComLarksuiteOapiSdkGo3ServiceWorkplace1Declared
}
