// Code generated by define_gene; DO NOT EDIT.
package larktranslation

import (
	_ "embed"
	"github.com/ZenLiuCN/engine"

	_ "github.com/ZenLiuCN/engine/modules/golang/context"
	_ "github.com/ZenLiuCN/engineX/modules/github/com/larksuite/oapi-sdk-go/v3/core"
	"github.com/larksuite/oapi-sdk-go/v3/service/translation/v1"
)

var (
	//go:embed github_com_larksuite_oapi-sdk-go_v3_service_translation_v1.d.ts
	GithubComLarksuiteOapiSdkGo3ServiceTranslation1Define   []byte
	GithubComLarksuiteOapiSdkGo3ServiceTranslation1Declared = map[string]any{
		"newDetectTextPathReqBodyBuilder":    larktranslation.NewDetectTextPathReqBodyBuilder,
		"newTranslateTextReqBodyBuilder":     larktranslation.NewTranslateTextReqBodyBuilder,
		"newDepartmentIdBuilder":             larktranslation.NewDepartmentIdBuilder,
		"newDetectTextReqBodyBuilder":        larktranslation.NewDetectTextReqBodyBuilder,
		"newDetectTextReqBuilder":            larktranslation.NewDetectTextReqBuilder,
		"newTermBuilder":                     larktranslation.NewTermBuilder,
		"newTranslateTextPathReqBodyBuilder": larktranslation.NewTranslateTextPathReqBodyBuilder,
		"newTranslateTextReqBuilder":         larktranslation.NewTranslateTextReqBuilder,
		"New":                                larktranslation.New,

		"emptyDetectTextReq":            engine.Empty[larktranslation.DetectTextReq],
		"emptyRefDetectTextReq":         engine.EmptyRefer[larktranslation.DetectTextReq],
		"refOfDetectTextReq":            engine.ReferOf[larktranslation.DetectTextReq],
		"unRefDetectTextReq":            engine.UnRefer[larktranslation.DetectTextReq],
		"emptyDetectTextResp":           engine.Empty[larktranslation.DetectTextResp],
		"emptyRefDetectTextResp":        engine.EmptyRefer[larktranslation.DetectTextResp],
		"refOfDetectTextResp":           engine.ReferOf[larktranslation.DetectTextResp],
		"unRefDetectTextResp":           engine.UnRefer[larktranslation.DetectTextResp],
		"emptyTerm":                     engine.Empty[larktranslation.Term],
		"emptyRefTerm":                  engine.EmptyRefer[larktranslation.Term],
		"refOfTerm":                     engine.ReferOf[larktranslation.Term],
		"unRefTerm":                     engine.UnRefer[larktranslation.Term],
		"emptyTranslateTextResp":        engine.Empty[larktranslation.TranslateTextResp],
		"emptyRefTranslateTextResp":     engine.EmptyRefer[larktranslation.TranslateTextResp],
		"refOfTranslateTextResp":        engine.ReferOf[larktranslation.TranslateTextResp],
		"unRefTranslateTextResp":        engine.UnRefer[larktranslation.TranslateTextResp],
		"emptyTranslateTextRespData":    engine.Empty[larktranslation.TranslateTextRespData],
		"emptyRefTranslateTextRespData": engine.EmptyRefer[larktranslation.TranslateTextRespData],
		"refOfTranslateTextRespData":    engine.ReferOf[larktranslation.TranslateTextRespData],
		"unRefTranslateTextRespData":    engine.UnRefer[larktranslation.TranslateTextRespData],
		"emptyDepartmentId":             engine.Empty[larktranslation.DepartmentId],
		"emptyRefDepartmentId":          engine.EmptyRefer[larktranslation.DepartmentId],
		"refOfDepartmentId":             engine.ReferOf[larktranslation.DepartmentId],
		"unRefDepartmentId":             engine.UnRefer[larktranslation.DepartmentId],
		"emptyDetectTextReqBody":        engine.Empty[larktranslation.DetectTextReqBody],
		"emptyRefDetectTextReqBody":     engine.EmptyRefer[larktranslation.DetectTextReqBody],
		"refOfDetectTextReqBody":        engine.ReferOf[larktranslation.DetectTextReqBody],
		"unRefDetectTextReqBody":        engine.UnRefer[larktranslation.DetectTextReqBody],
		"emptyTranslateTextReqBody":     engine.Empty[larktranslation.TranslateTextReqBody],
		"emptyRefTranslateTextReqBody":  engine.EmptyRefer[larktranslation.TranslateTextReqBody],
		"refOfTranslateTextReqBody":     engine.ReferOf[larktranslation.TranslateTextReqBody],
		"unRefTranslateTextReqBody":     engine.UnRefer[larktranslation.TranslateTextReqBody],
		"emptyDetectTextRespData":       engine.Empty[larktranslation.DetectTextRespData],
		"emptyRefDetectTextRespData":    engine.EmptyRefer[larktranslation.DetectTextRespData],
		"refOfDetectTextRespData":       engine.ReferOf[larktranslation.DetectTextRespData],
		"unRefDetectTextRespData":       engine.UnRefer[larktranslation.DetectTextRespData],
		"emptyV1":                       engine.Empty[larktranslation.V1],
		"emptyRefV1":                    engine.EmptyRefer[larktranslation.V1],
		"refOfV1":                       engine.ReferOf[larktranslation.V1],
		"unRefV1":                       engine.UnRefer[larktranslation.V1],
		"emptyTranslateTextReq":         engine.Empty[larktranslation.TranslateTextReq],
		"emptyRefTranslateTextReq":      engine.EmptyRefer[larktranslation.TranslateTextReq],
		"refOfTranslateTextReq":         engine.ReferOf[larktranslation.TranslateTextReq],
		"unRefTranslateTextReq":         engine.UnRefer[larktranslation.TranslateTextReq]}
)

func init() {
	engine.RegisterModule(GithubComLarksuiteOapiSdkGo3ServiceTranslation1Module{})
}

type GithubComLarksuiteOapiSdkGo3ServiceTranslation1Module struct{}

func (S GithubComLarksuiteOapiSdkGo3ServiceTranslation1Module) Identity() string {
	return "github.com/larksuite/oapi-sdk-go/v3/service/translation/v1"
}
func (S GithubComLarksuiteOapiSdkGo3ServiceTranslation1Module) TypeDefine() []byte {
	return GithubComLarksuiteOapiSdkGo3ServiceTranslation1Define
}
func (S GithubComLarksuiteOapiSdkGo3ServiceTranslation1Module) Exports() map[string]any {
	return GithubComLarksuiteOapiSdkGo3ServiceTranslation1Declared
}
