// Code generated by define_gene; DO NOT EDIT.
package compensation

import (
	_ "embed"
	"github.com/ZenLiuCN/engine"

	_ "github.com/ZenLiuCN/engineX/modules/github/com/larksuite/oapi-sdk-go/v3/core"
	_ "github.com/ZenLiuCN/engineX/modules/github/com/larksuite/oapi-sdk-go/v3/service/compensation/v1"
	"github.com/larksuite/oapi-sdk-go/v3/service/compensation"
)

var (
	//go:embed github_com_larksuite_oapi-sdk-go_v3_service_compensation.d.ts
	GithubComLarksuiteOapiSdkGo3ServiceCompensationDefine   []byte
	GithubComLarksuiteOapiSdkGo3ServiceCompensationDeclared = map[string]any{
		"newService": compensation.NewService,
	}
)

func init() {
	engine.RegisterModule(GithubComLarksuiteOapiSdkGo3ServiceCompensationModule{})
}

type GithubComLarksuiteOapiSdkGo3ServiceCompensationModule struct{}

func (S GithubComLarksuiteOapiSdkGo3ServiceCompensationModule) Identity() string {
	return "github.com/larksuite/oapi-sdk-go/v3/service/compensation"
}
func (S GithubComLarksuiteOapiSdkGo3ServiceCompensationModule) TypeDefine() []byte {
	return GithubComLarksuiteOapiSdkGo3ServiceCompensationDefine
}
func (S GithubComLarksuiteOapiSdkGo3ServiceCompensationModule) Exports() map[string]any {
	return GithubComLarksuiteOapiSdkGo3ServiceCompensationDeclared
}
