// Code generated by define_gene; DO NOT EDIT.
package larkauth

import (
	_ "embed"
	"github.com/ZenLiuCN/engine"

	_ "github.com/ZenLiuCN/engine/modules/golang/context"
	_ "github.com/ZenLiuCN/engineX/modules/github/com/larksuite/oapi-sdk-go/v3/core"
	"github.com/larksuite/oapi-sdk-go/v3/service/auth/v3"
)

var (
	//go:embed github_com_larksuite_oapi-sdk-go_v3_service_auth_v3.d.ts
	GithubComLarksuiteOapiSdkGo3ServiceAuth3Define   []byte
	GithubComLarksuiteOapiSdkGo3ServiceAuth3Declared = map[string]any{
		"newResendAppTicketReqBodyBuilder":               larkauth.NewResendAppTicketReqBodyBuilder,
		"newResendAppTicketReqBuilder":                   larkauth.NewResendAppTicketReqBuilder,
		"newRevokeTokenEventBuilder":                     larkauth.NewRevokeTokenEventBuilder,
		"newResendAppTicketPathReqBodyBuilder":           larkauth.NewResendAppTicketPathReqBodyBuilder,
		"newInternalAppAccessTokenPathReqBodyBuilder":    larkauth.NewInternalAppAccessTokenPathReqBodyBuilder,
		"newInternalTenantAccessTokenReqBodyBuilder":     larkauth.NewInternalTenantAccessTokenReqBodyBuilder,
		"newInternalTenantAccessTokenReqBuilder":         larkauth.NewInternalTenantAccessTokenReqBuilder,
		"newCreateTenantAccessTokenReqBodyBuilder":       larkauth.NewCreateTenantAccessTokenReqBodyBuilder,
		"newCreateTenantAccessTokenReqBuilder":           larkauth.NewCreateTenantAccessTokenReqBuilder,
		"newInternalAppAccessTokenReqBuilder":            larkauth.NewInternalAppAccessTokenReqBuilder,
		"newInternalTenantAccessTokenPathReqBodyBuilder": larkauth.NewInternalTenantAccessTokenPathReqBodyBuilder,
		"newCreateAppAccessTokenPathReqBodyBuilder":      larkauth.NewCreateAppAccessTokenPathReqBodyBuilder,
		"newCreateAppAccessTokenReqBodyBuilder":          larkauth.NewCreateAppAccessTokenReqBodyBuilder,
		"newCreateTenantAccessTokenPathReqBodyBuilder":   larkauth.NewCreateTenantAccessTokenPathReqBodyBuilder,
		"newInternalAppAccessTokenReqBodyBuilder":        larkauth.NewInternalAppAccessTokenReqBodyBuilder,
		"New":                               larkauth.New,
		"newCreateAppAccessTokenReqBuilder": larkauth.NewCreateAppAccessTokenReqBuilder,
		"newDepartmentIdBuilder":            larkauth.NewDepartmentIdBuilder,

		"emptyInternalTenantAccessTokenReqBody":    engine.Empty[larkauth.InternalTenantAccessTokenReqBody],
		"emptyRefInternalTenantAccessTokenReqBody": engine.EmptyRefer[larkauth.InternalTenantAccessTokenReqBody],
		"refOfInternalTenantAccessTokenReqBody":    engine.ReferOf[larkauth.InternalTenantAccessTokenReqBody],
		"unRefInternalTenantAccessTokenReqBody":    engine.UnRefer[larkauth.InternalTenantAccessTokenReqBody],
		"emptyInternalTenantAccessTokenResp":       engine.Empty[larkauth.InternalTenantAccessTokenResp],
		"emptyRefInternalTenantAccessTokenResp":    engine.EmptyRefer[larkauth.InternalTenantAccessTokenResp],
		"refOfInternalTenantAccessTokenResp":       engine.ReferOf[larkauth.InternalTenantAccessTokenResp],
		"unRefInternalTenantAccessTokenResp":       engine.UnRefer[larkauth.InternalTenantAccessTokenResp],
		"emptyRevokeTokenEvent":                    engine.Empty[larkauth.RevokeTokenEvent],
		"emptyRefRevokeTokenEvent":                 engine.EmptyRefer[larkauth.RevokeTokenEvent],
		"refOfRevokeTokenEvent":                    engine.ReferOf[larkauth.RevokeTokenEvent],
		"unRefRevokeTokenEvent":                    engine.UnRefer[larkauth.RevokeTokenEvent],
		"emptyCreateTenantAccessTokenReqBody":      engine.Empty[larkauth.CreateTenantAccessTokenReqBody],
		"emptyRefCreateTenantAccessTokenReqBody":   engine.EmptyRefer[larkauth.CreateTenantAccessTokenReqBody],
		"refOfCreateTenantAccessTokenReqBody":      engine.ReferOf[larkauth.CreateTenantAccessTokenReqBody],
		"unRefCreateTenantAccessTokenReqBody":      engine.UnRefer[larkauth.CreateTenantAccessTokenReqBody],
		"emptyInternalAppAccessTokenReqBody":       engine.Empty[larkauth.InternalAppAccessTokenReqBody],
		"emptyRefInternalAppAccessTokenReqBody":    engine.EmptyRefer[larkauth.InternalAppAccessTokenReqBody],
		"refOfInternalAppAccessTokenReqBody":       engine.ReferOf[larkauth.InternalAppAccessTokenReqBody],
		"unRefInternalAppAccessTokenReqBody":       engine.UnRefer[larkauth.InternalAppAccessTokenReqBody],
		"emptyResendAppTicketReq":                  engine.Empty[larkauth.ResendAppTicketReq],
		"emptyRefResendAppTicketReq":               engine.EmptyRefer[larkauth.ResendAppTicketReq],
		"refOfResendAppTicketReq":                  engine.ReferOf[larkauth.ResendAppTicketReq],
		"unRefResendAppTicketReq":                  engine.UnRefer[larkauth.ResendAppTicketReq],
		"emptyCreateAppAccessTokenReqBody":         engine.Empty[larkauth.CreateAppAccessTokenReqBody],
		"emptyRefCreateAppAccessTokenReqBody":      engine.EmptyRefer[larkauth.CreateAppAccessTokenReqBody],
		"refOfCreateAppAccessTokenReqBody":         engine.ReferOf[larkauth.CreateAppAccessTokenReqBody],
		"unRefCreateAppAccessTokenReqBody":         engine.UnRefer[larkauth.CreateAppAccessTokenReqBody],
		"emptyInternalTenantAccessTokenReq":        engine.Empty[larkauth.InternalTenantAccessTokenReq],
		"emptyRefInternalTenantAccessTokenReq":     engine.EmptyRefer[larkauth.InternalTenantAccessTokenReq],
		"refOfInternalTenantAccessTokenReq":        engine.ReferOf[larkauth.InternalTenantAccessTokenReq],
		"unRefInternalTenantAccessTokenReq":        engine.UnRefer[larkauth.InternalTenantAccessTokenReq],
		"emptyCreateTenantAccessTokenResp":         engine.Empty[larkauth.CreateTenantAccessTokenResp],
		"emptyRefCreateTenantAccessTokenResp":      engine.EmptyRefer[larkauth.CreateTenantAccessTokenResp],
		"refOfCreateTenantAccessTokenResp":         engine.ReferOf[larkauth.CreateTenantAccessTokenResp],
		"unRefCreateTenantAccessTokenResp":         engine.UnRefer[larkauth.CreateTenantAccessTokenResp],
		"emptyCreateAppAccessTokenResp":            engine.Empty[larkauth.CreateAppAccessTokenResp],
		"emptyRefCreateAppAccessTokenResp":         engine.EmptyRefer[larkauth.CreateAppAccessTokenResp],
		"refOfCreateAppAccessTokenResp":            engine.ReferOf[larkauth.CreateAppAccessTokenResp],
		"unRefCreateAppAccessTokenResp":            engine.UnRefer[larkauth.CreateAppAccessTokenResp],
		"emptyCreateTenantAccessTokenReq":          engine.Empty[larkauth.CreateTenantAccessTokenReq],
		"emptyRefCreateTenantAccessTokenReq":       engine.EmptyRefer[larkauth.CreateTenantAccessTokenReq],
		"refOfCreateTenantAccessTokenReq":          engine.ReferOf[larkauth.CreateTenantAccessTokenReq],
		"unRefCreateTenantAccessTokenReq":          engine.UnRefer[larkauth.CreateTenantAccessTokenReq],
		"emptyDepartmentId":                        engine.Empty[larkauth.DepartmentId],
		"emptyRefDepartmentId":                     engine.EmptyRefer[larkauth.DepartmentId],
		"refOfDepartmentId":                        engine.ReferOf[larkauth.DepartmentId],
		"unRefDepartmentId":                        engine.UnRefer[larkauth.DepartmentId],
		"emptyCreateAppAccessTokenReq":             engine.Empty[larkauth.CreateAppAccessTokenReq],
		"emptyRefCreateAppAccessTokenReq":          engine.EmptyRefer[larkauth.CreateAppAccessTokenReq],
		"refOfCreateAppAccessTokenReq":             engine.ReferOf[larkauth.CreateAppAccessTokenReq],
		"unRefCreateAppAccessTokenReq":             engine.UnRefer[larkauth.CreateAppAccessTokenReq],
		"emptyInternalAppAccessTokenReq":           engine.Empty[larkauth.InternalAppAccessTokenReq],
		"emptyRefInternalAppAccessTokenReq":        engine.EmptyRefer[larkauth.InternalAppAccessTokenReq],
		"refOfInternalAppAccessTokenReq":           engine.ReferOf[larkauth.InternalAppAccessTokenReq],
		"unRefInternalAppAccessTokenReq":           engine.UnRefer[larkauth.InternalAppAccessTokenReq],
		"emptyResendAppTicketResp":                 engine.Empty[larkauth.ResendAppTicketResp],
		"emptyRefResendAppTicketResp":              engine.EmptyRefer[larkauth.ResendAppTicketResp],
		"refOfResendAppTicketResp":                 engine.ReferOf[larkauth.ResendAppTicketResp],
		"unRefResendAppTicketResp":                 engine.UnRefer[larkauth.ResendAppTicketResp],
		"emptyV3":                                  engine.Empty[larkauth.V3],
		"emptyRefV3":                               engine.EmptyRefer[larkauth.V3],
		"refOfV3":                                  engine.ReferOf[larkauth.V3],
		"unRefV3":                                  engine.UnRefer[larkauth.V3],
		"emptyInternalAppAccessTokenResp":          engine.Empty[larkauth.InternalAppAccessTokenResp],
		"emptyRefInternalAppAccessTokenResp":       engine.EmptyRefer[larkauth.InternalAppAccessTokenResp],
		"refOfInternalAppAccessTokenResp":          engine.ReferOf[larkauth.InternalAppAccessTokenResp],
		"unRefInternalAppAccessTokenResp":          engine.UnRefer[larkauth.InternalAppAccessTokenResp],
		"emptyResendAppTicketReqBody":              engine.Empty[larkauth.ResendAppTicketReqBody],
		"emptyRefResendAppTicketReqBody":           engine.EmptyRefer[larkauth.ResendAppTicketReqBody],
		"refOfResendAppTicketReqBody":              engine.ReferOf[larkauth.ResendAppTicketReqBody],
		"unRefResendAppTicketReqBody":              engine.UnRefer[larkauth.ResendAppTicketReqBody]}
)

func init() {
	engine.RegisterModule(GithubComLarksuiteOapiSdkGo3ServiceAuth3Module{})
}

type GithubComLarksuiteOapiSdkGo3ServiceAuth3Module struct{}

func (S GithubComLarksuiteOapiSdkGo3ServiceAuth3Module) Identity() string {
	return "github.com/larksuite/oapi-sdk-go/v3/service/auth/v3"
}
func (S GithubComLarksuiteOapiSdkGo3ServiceAuth3Module) TypeDefine() []byte {
	return GithubComLarksuiteOapiSdkGo3ServiceAuth3Define
}
func (S GithubComLarksuiteOapiSdkGo3ServiceAuth3Module) Exports() map[string]any {
	return GithubComLarksuiteOapiSdkGo3ServiceAuth3Declared
}
