// Code generated by define_gene; DO NOT EDIT.
package ws

import (
	_ "embed"
	"github.com/ZenLiuCN/engine"

	_ "github.com/ZenLiuCN/engine/modules/golang/context"
	_ "github.com/ZenLiuCN/engine/modules/golang/encoding/json"
	_ "github.com/ZenLiuCN/engine/modules/golang/fmt"
	_ "github.com/ZenLiuCN/engineX/modules/github/com/larksuite/oapi-sdk-go/v3/core"
	_ "github.com/ZenLiuCN/engineX/modules/github/com/larksuite/oapi-sdk-go/v3/event/dispatcher"
	"github.com/larksuite/oapi-sdk-go/v3/ws"
)

var (
	//go:embed github_com_larksuite_oapi-sdk-go_v3_ws.d.ts
	GithubComLarksuiteOapiSdkGo3WsDefine   []byte
	GithubComLarksuiteOapiSdkGo3WsDeclared = map[string]any{
		"AuthFailed":                   ws.AuthFailed,
		"HeaderInstanceID":             ws.HeaderInstanceID,
		"newClient":                    ws.NewClient,
		"withEventHandler":             ws.WithEventHandler,
		"HeaderBizRt":                  ws.HeaderBizRt,
		"HeaderHandshakeStatus":        ws.HeaderHandshakeStatus,
		"HeaderMessageID":              ws.HeaderMessageID,
		"HeaderTraceID":                ws.HeaderTraceID,
		"HeaderSum":                    ws.HeaderSum,
		"HeaderTimestamp":              ws.HeaderTimestamp,
		"InternalError":                ws.InternalError,
		"MessageTypePong":              ws.MessageTypePong,
		"ErrUnexpectedEndOfGroupPbbp2": ws.ErrUnexpectedEndOfGroupPbbp2,
		"Forbidden":                    ws.Forbidden,
		"FrameTypeControl":             ws.FrameTypeControl,
		"HeaderHandshakeMsg":           ws.HeaderHandshakeMsg,
		"newPingFrame":                 ws.NewPingFrame,
		"newServerError":               ws.NewServerError,
		"OK":                           ws.OK,
		"FrameTypeData":                ws.FrameTypeData,
		"HeaderHandshakeAuthErrCode":   ws.HeaderHandshakeAuthErrCode,
		"withAutoReconnect":            ws.WithAutoReconnect,
		"withDomain":                   ws.WithDomain,
		"ErrInvalidLengthPbbp2":        ws.ErrInvalidLengthPbbp2,
		"ExceedConnLimit":              ws.ExceedConnLimit,
		"HeaderSeq":                    ws.HeaderSeq,
		"ErrIntOverflowPbbp2":          ws.ErrIntOverflowPbbp2,
		"ServiceID":                    ws.ServiceID,
		"newResponseByCode":            ws.NewResponseByCode,
		"withLogLevel":                 ws.WithLogLevel,
		"MessageTypeCard":              ws.MessageTypeCard,
		"MessageTypeEvent":             ws.MessageTypeEvent,
		"MessageTypePing":              ws.MessageTypePing,
		"newClientError":               ws.NewClientError,
		"withLogger":                   ws.WithLogger,
		"DeviceID":                     ws.DeviceID,
		"GenEndpointUri":               ws.GenEndpointUri,
		"HeaderType":                   ws.HeaderType,
		"SystemBusy":                   ws.SystemBusy,

		"emptyClientConfig":    engine.Empty[ws.ClientConfig],
		"emptyRefClientConfig": engine.EmptyRefer[ws.ClientConfig],
		"refOfClientConfig":    engine.ReferOf[ws.ClientConfig],
		"unRefClientConfig":    engine.UnRefer[ws.ClientConfig],
		"emptyResponse":        engine.Empty[ws.Response],
		"emptyRefResponse":     engine.EmptyRefer[ws.Response],
		"refOfResponse":        engine.ReferOf[ws.Response],
		"unRefResponse":        engine.UnRefer[ws.Response],
		"emptyEndpoint":        engine.Empty[ws.Endpoint],
		"emptyRefEndpoint":     engine.EmptyRefer[ws.Endpoint],
		"refOfEndpoint":        engine.ReferOf[ws.Endpoint],
		"unRefEndpoint":        engine.UnRefer[ws.Endpoint],
		"emptyEndpointResp":    engine.Empty[ws.EndpointResp],
		"emptyRefEndpointResp": engine.EmptyRefer[ws.EndpointResp],
		"refOfEndpointResp":    engine.ReferOf[ws.EndpointResp],
		"unRefEndpointResp":    engine.UnRefer[ws.EndpointResp],
		"emptyFrame":           engine.Empty[ws.Frame],
		"emptyRefFrame":        engine.EmptyRefer[ws.Frame],
		"refOfFrame":           engine.ReferOf[ws.Frame],
		"unRefFrame":           engine.UnRefer[ws.Frame],
		"emptyHeader":          engine.Empty[ws.Header],
		"emptyRefHeader":       engine.EmptyRefer[ws.Header],
		"refOfHeader":          engine.ReferOf[ws.Header],
		"unRefHeader":          engine.UnRefer[ws.Header]}
)

func init() {
	engine.RegisterModule(GithubComLarksuiteOapiSdkGo3WsModule{})
}

type GithubComLarksuiteOapiSdkGo3WsModule struct{}

func (S GithubComLarksuiteOapiSdkGo3WsModule) Identity() string {
	return "github.com/larksuite/oapi-sdk-go/v3/ws"
}
func (S GithubComLarksuiteOapiSdkGo3WsModule) TypeDefine() []byte {
	return GithubComLarksuiteOapiSdkGo3WsDefine
}
func (S GithubComLarksuiteOapiSdkGo3WsModule) Exports() map[string]any {
	return GithubComLarksuiteOapiSdkGo3WsDeclared
}
