// Code generated by define_gene; DO NOT EDIT.
package larkcard

import (
	_ "embed"
	"github.com/ZenLiuCN/engine"

	_ "github.com/ZenLiuCN/engine/modules/golang/context"
	_ "github.com/ZenLiuCN/engine/modules/golang/encoding/json"
	_ "github.com/ZenLiuCN/engineX/modules/github/com/larksuite/oapi-sdk-go/v3/core"
	_ "github.com/ZenLiuCN/engineX/modules/github/com/larksuite/oapi-sdk-go/v3/event"
	"github.com/larksuite/oapi-sdk-go/v3/card"
)

var (
	//go:embed github_com_larksuite_oapi-sdk-go_v3_card.d.ts
	GithubComLarksuiteOapiSdkGo3CardDefine   []byte
	GithubComLarksuiteOapiSdkGo3CardDeclared = map[string]any{
		"newMessageCardEmbedButton":           larkcard.NewMessageCardEmbedButton,
		"MessageCardActionLayoutTrisection":   larkcard.MessageCardActionLayoutTrisection,
		"newMessageCardEmbedDatePickerBase":   larkcard.NewMessageCardEmbedDatePickerBase,
		"newMessageCardEmbedPickerDatetime":   larkcard.NewMessageCardEmbedPickerDatetime,
		"TemplateYellow":                      larkcard.TemplateYellow,
		"newMessageCardEmbedDatePicker":       larkcard.NewMessageCardEmbedDatePicker,
		"newMessageCardEmbedPickerTime":       larkcard.NewMessageCardEmbedPickerTime,
		"MessageCardButtonTypeDefault":        larkcard.MessageCardButtonTypeDefault,
		"MessageCardImageModelCropCenter":     larkcard.MessageCardImageModelCropCenter,
		"newMessageCardConfig":                larkcard.NewMessageCardConfig,
		"newMessageCardHr":                    larkcard.NewMessageCardHr,
		"newMessageCardLarkMd":                larkcard.NewMessageCardLarkMd,
		"newMessageCardEmbedOverflow":         larkcard.NewMessageCardEmbedOverflow,
		"newMessageCardEmbedSelectMenuPerson": larkcard.NewMessageCardEmbedSelectMenuPerson,
		"TemplateGreen":                       larkcard.TemplateGreen,
		"TemplateIndigo":                      larkcard.TemplateIndigo,
		"MessageCardActionLayoutBisected":     larkcard.MessageCardActionLayoutBisected,
		"newMessageCardPlainText":             larkcard.NewMessageCardPlainText,
		"MessageCardImageModelFitHorizontal":  larkcard.MessageCardImageModelFitHorizontal,
		"newMessageCardImage":                 larkcard.NewMessageCardImage,
		"TemplateRed":                         larkcard.TemplateRed,
		"newMessageCardEmbedSelectOption":     larkcard.NewMessageCardEmbedSelectOption,
		"newMessageCardI18nElements":          larkcard.NewMessageCardI18nElements,
		"newMessageCardEmbedImage":            larkcard.NewMessageCardEmbedImage,
		"newMessageCardEmbedSelectMenuBase":   larkcard.NewMessageCardEmbedSelectMenuBase,
		"TemplateTurquoise":                   larkcard.TemplateTurquoise,
		"MessageCardActionLayoutFlow":         larkcard.MessageCardActionLayoutFlow,
		"newMessageCardActionConfirm":         larkcard.NewMessageCardActionConfirm,
		"newMessageCardHeader":                larkcard.NewMessageCardHeader,
		"TemplateCarmine":                     larkcard.TemplateCarmine,
		"TemplateGrey":                        larkcard.TemplateGrey,
		"newMessageCardDiv":                   larkcard.NewMessageCardDiv,
		"MessageCardButtonTypeDanger":         larkcard.MessageCardButtonTypeDanger,
		"newMessageCardNote":                  larkcard.NewMessageCardNote,
		"newMessageCardPlainTextI18n":         larkcard.NewMessageCardPlainTextI18n,
		"signature":                           larkcard.Signature,
		"TemplateBlue":                        larkcard.TemplateBlue,
		"MessageCardButtonTypePrimary":        larkcard.MessageCardButtonTypePrimary,
		"newCardActionHandler":                larkcard.NewCardActionHandler,
		"TemplateOrange":                      larkcard.TemplateOrange,
		"TemplateViolet":                      larkcard.TemplateViolet,
		"TemplateWathet":                      larkcard.TemplateWathet,
		"newMessageCardURL":                   larkcard.NewMessageCardURL,
		"newMessageCardEmbedSelectMenuStatic": larkcard.NewMessageCardEmbedSelectMenuStatic,
		"newMessageCardField":                 larkcard.NewMessageCardField,
		"newMessageCard":                      larkcard.NewMessageCard,
		"newMessageCardAction":                larkcard.NewMessageCardAction,
		"newMessageCardMarkdown":              larkcard.NewMessageCardMarkdown,
		"TemplatePurple":                      larkcard.TemplatePurple,

		"emptyCardActionBody":     engine.Empty[larkcard.CardActionBody],
		"emptyRefCardActionBody":  engine.EmptyRefer[larkcard.CardActionBody],
		"refOfCardActionBody":     engine.ReferOf[larkcard.CardActionBody],
		"unRefCardActionBody":     engine.UnRefer[larkcard.CardActionBody],
		"emptyCustomToastBody":    engine.Empty[larkcard.CustomToastBody],
		"emptyRefCustomToastBody": engine.EmptyRefer[larkcard.CustomToastBody],
		"refOfCustomToastBody":    engine.ReferOf[larkcard.CustomToastBody],
		"unRefCustomToastBody":    engine.UnRefer[larkcard.CustomToastBody],
		"emptyI18n":               engine.Empty[larkcard.I18n],
		"emptyRefI18n":            engine.EmptyRefer[larkcard.I18n],
		"refOfI18n":               engine.ReferOf[larkcard.I18n],
		"unRefI18n":               engine.UnRefer[larkcard.I18n],
		"emptyCustomResp":         engine.Empty[larkcard.CustomResp],
		"emptyRefCustomResp":      engine.EmptyRefer[larkcard.CustomResp],
		"refOfCustomResp":         engine.ReferOf[larkcard.CustomResp],
		"unRefCustomResp":         engine.UnRefer[larkcard.CustomResp],
		"emptyCardAction":         engine.Empty[larkcard.CardAction],
		"emptyRefCardAction":      engine.EmptyRefer[larkcard.CardAction],
		"refOfCardAction":         engine.ReferOf[larkcard.CardAction],
		"unRefCardAction":         engine.UnRefer[larkcard.CardAction]}
)

func init() {
	engine.RegisterModule(GithubComLarksuiteOapiSdkGo3CardModule{})
}

type GithubComLarksuiteOapiSdkGo3CardModule struct{}

func (S GithubComLarksuiteOapiSdkGo3CardModule) Identity() string {
	return "github.com/larksuite/oapi-sdk-go/v3/card"
}
func (S GithubComLarksuiteOapiSdkGo3CardModule) TypeDefine() []byte {
	return GithubComLarksuiteOapiSdkGo3CardDefine
}
func (S GithubComLarksuiteOapiSdkGo3CardModule) Exports() map[string]any {
	return GithubComLarksuiteOapiSdkGo3CardDeclared
}
